import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import { BsFillMoonStarsFill } from "react-icons/bs";

import Navigation from "./Navigation";
import Slider from "./Slider";
import Services from "./Services";
import Work from "./work";
import Contact from "./Contact";
import Footer from "./Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <div className="min-h-screen bg-white dark:bg-gray-900 text-black dark:text-white ">
        <Head>
          <title>JhEd Portafolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navigation setDarkMode={setDarkMode} darkMode={darkMode} />
        <br/>
        <br/>
        <main className="px-10 py-10">
           <Slider />
           <Services darkMode={darkMode}/>
           <Work />
           <Contact />
           <Footer darkMode={darkMode}/>
        </main>
      </div>
    </div>
  );
}
